# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 264)
        Dialog.setMinimumSize(QtCore.QSize(557, 264))
        Dialog.setMaximumSize(QtCore.QSize(557, 264))
        self.tipsLabel = QtWidgets.QLabel(Dialog)
        self.tipsLabel.setGeometry(QtCore.QRect(10, -10, 541, 71))
        self.tipsLabel.setObjectName("tipsLabel")
        self.checkButton = QtWidgets.QPushButton(Dialog)
        self.checkButton.setGeometry(QtCore.QRect(450, 220, 101, 41))
        self.checkButton.setObjectName("checkButton")
        self.updateButton = QtWidgets.QPushButton(Dialog)
        self.updateButton.setGeometry(QtCore.QRect(340, 220, 101, 41))
        self.updateButton.setObjectName("updateButton")
        self.downloadprogressBar = QtWidgets.QProgressBar(Dialog)
        self.downloadprogressBar.setGeometry(QtCore.QRect(10, 220, 321, 31))
        self.downloadprogressBar.setProperty("value", 0)
        self.downloadprogressBar.setObjectName("downloadprogressBar")
        self.updateInfo = QtWidgets.QTextBrowser(Dialog)
        self.updateInfo.setGeometry(QtCore.QRect(10, 60, 541, 151))
        self.updateInfo.setDocumentTitle("")
        self.updateInfo.setObjectName("updateInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Updater"))
        self.tipsLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Click the button which is named &quot;Check&quot; to check any available</span></p><p><span style=\" font-size:11pt;\">software update.</span></p></body></html>"))
        self.checkButton.setText(_translate("Dialog", "Check"))
        self.updateButton.setText(_translate("Dialog", "Update"))
        self.updateInfo.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
